### ISSUE TITLE
Make the interface to customize the chatbot available for the users directly

### ISSUE THREAD

**Issue by doubianimehdiefor** [ragapp/ragapp#10]
I would like the RAGapp to integrate a user-friendly interface for creating custom GPTs, similar to the one offered by OpenAI, that can be used directly by users , basically keep the UI and remove the backend related features like the api key.

This interface should allow users to:
Name and personalize their GPT (name, profile picture).
Provide examples of desired behaviors through text prompts.
Upload documents to enrich the GPT's knowledge base.
Configure integrations with external APIs for advanced functionalities.
Publish and share their GPT easily.

Describe alternatives you've considered
I have considered using external tools like those offered by OpenAI to create GPTs, but this requires juggling multiple platforms and having advanced technical skills. Another alternative would be to develop a custom internal solution, but this would require significant resources in terms of time and development.

Additional context
Integrating this feature into RAGapp would democratize the creation of GPTs and make this technology accessible to a wider range of users, including those without technical skills. This could also increase user engagement and the added value of the application. Here are some screenshots of OpenAI's GPT creation interface for reference

**Comment by marcusschiesser** [comment]
@doubianimehdiefor most of the features that you mention are already in RAGapp - which one is missing for you?

**Comment by doubianimehdiefor** [comment]
What I mean is in the chatbot directly , USERS should have the possibility to make their own GPTs using RAGAPP interface (just like in chatgpt) , from what I understand, allows to make GPTs that are then released to USERS ... 
![image](https://github.com/ragapp/ragapp/assets/154507236/61972d4a-8a42-4b40-be25-27168e663828)
I don't know if my request clear :)

**Comment by marcusschiesser** [comment]
Ah I got it. That's not the scope of this project. The idea is to have one docker container per "GPT". If you need another one, deploy another docker container
