### ISSUE TITLE
Latests changes broke retrieving files uploaded

### ISSUE THREAD

**Issue by juanviamonte** [ragapp/ragapp#124]
**Describe the bug**
The Docker image is still working ok.

I've been running the project locally using `make dev`, for a few weeks things are going ok
Today i pulled the latest from main branch and things stopped working
In the /admin path i configured my model and knowledge

I have 2 files uploaded 
<img width="739" alt="image" src="https://github.com/user-attachments/assets/720414c9-39f6-436f-8eea-99dc3c98f52e">

But when i ask questions in the right side it seems to be using the files that are uploaded into the Knowledge section

Example
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/e82495e9-7be6-4c36-a11f-7a1dc20f42d6">

**To Reproduce**
```
poetry install --no-root
make build-frontends
make dev
```

Visit http://0.0.0.0:8000/admin/ and configure things, OpenAI with the key example:
<img width="735" alt="image" src="https://github.com/user-attachments/assets/824456b0-0ee3-4a84-8633-4bc3976e36a4">

In the knowledge section upload a file  or two 
<img width="721" alt="image" src="https://github.com/user-attachments/assets/900a7cd3-098a-49f2-b3e4-d874866146f9">

Then try asking questions about the content of those files and will not know anything about the files uploaded

**Expected behavior**
Should retrieve the files content for context before sending to the LLM for inference

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcusschiesser** [comment]
@juanviamonte issue was fixed upstream and the fix is now in `main` branch
