### ISSUE TITLE
Can't pass through the manager login and updating credentials wont work

### ISSUE THREAD

**Issue by benjaminbascary97** [ragapp/ragapp#131]
**Describe the bug**
Can't pass through the manager login with default credentials and updating credentials wont work.

**To Reproduce**
cd ragapp
cd deployments
cd multiple-ragapps
docker-compose up --build
visite localhost/manager
prompt for admin and admin

**Expected behavior**
Visiting localhost/manager app and prompt for admin & admin credentials should let me access the app

Even updating the hashed credential in the docker-compose file following the docs wont work. Network tab does not show any activity also.

**screenshots**
![imagen](https://github.com/user-attachments/assets/d527c4d9-72f7-462f-9fe1-a628da631c3a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser. Firefox

**Comment by marcusschiesser** [comment]
`docker-compose up --build` is using the local build - did you try `docker-compose up`? Please also make sure to either repull the latest images or to delete existing ones (so that Docker will pull the latest images)

**Comment by marcusschiesser** [comment]
@benjaminbascary97 I just checked the Docker doc, please try for re-pull:
```
docker compose pull
docker compose up
```

**Comment by marcusschiesser** [comment]
@benjaminbascary97 added `docker pull` to README. Can't reproduce your issue with the dev system. Please make sure that your checkout is clean (e.g. config files) and try again.

**Comment by benjaminbascary97** [comment]
Thank you @marcusschiesser for the quick response. Tried again using WSL2 and it works! but its the same in windows.. I suspect my issue was not related, sorry :( Forgot to try in linux before opening the issue. Any thoughts?

**Comment by marcusschiesser** [comment]
@benjaminbascary97 sorry currently this deployment only runs on Linux
