### ISSUE TITLE
Failed to run locally built docker container: entrypoint problem

### ISSUE THREAD

**Issue by ns-ffx** [ragapp/ragapp#148]
**Describe the bug**
I cloned the repo and build docker image and getting error while trying to run the docker image

**To Reproduce**
1) clone repo : git clone https://github.com/ragapp/ragapp.git
2) change to ragapp\src\ragapp directory
3) build docker image: docker build -t rag_26_08_2024_v1 .
4) try to run: docker run -p 8000:8000 rag_26_08_2024_v1

**Expected behavior**
Running docker container

 - OS: Windows 11
- most recent version 0.0.21

Error:
exec /app/entrypoint.sh: no such file or directory

**Comment by ns-ffx** [comment]
can you describe what the problem on my site is? don't want to download any file. Thank you!

**Comment by marcusschiesser** [comment]
Docker images are created in CI - should work if you follow the same commands as in CI: https://github.com/ragapp/ragapp/blob/main/.github/workflows/main_docker_images.yml
On windows better use WSL
