### ISSUE TITLE
Add support for Azure OpenAI as a provider

### ISSUE THREAD

**Issue by JayDoubleu** [ragapp/ragapp#16]
Currently, RAGapp supports OpenAI as the AI provider. However, it would be beneficial to also support Azure OpenAI as an alternative provider.

**Comment by marcusschiesser** [comment]
@JayDoubleu great idea. what parameters would you like to be configurable then?

**Comment by JayDoubleu** [comment]
I believe the below options would be a good start

```bash
export AZURE_OPENAI_ENDPOINT="your_azure_openai_endpoint"
export AZURE_OPENAI_API_KEY="your_azure_openai_api_key"
export AZURE_OPENAI_DEPLOYMENT_NAME="your_gpt35_turbo_deployment_name"
export AZURE_OPENAI_API_VERSION="your_api_version"  # Example: "2023-05-15"
```

**Comment by johnsmith491** [comment]
> Currently, RAGapp supports OpenAI as the AI provider. However, it would be beneficial to also support Azure OpenAI as an alternative provider.

Expanding RAGapp's AI provider support to include Azure OpenAI alongside the existing support for OpenAI would indeed offer users more flexibility and options. Here are some steps you might consider to implement this change:

1. **Assess Azure OpenAI's capabilities**: Evaluate Azure OpenAI's features, pricing, and compatibility with RAGapp's requirements to ensure it meets the necessary criteria for integration.

2. **Update RAGapp's backend**: Modify the backend infrastructure of RAGapp to accommodate Azure OpenAI as an additional AI provider. This might involve implementing new API endpoints, authentication mechanisms, and data processing logic specific to Azure OpenAI.

3. **Integrate Azure OpenAI SDK**: Incorporate the Azure OpenAI SDK into RAGapp's codebase to enable seamless interaction with Azure's AI services. This includes integrating functionalities such as text generation, question answering, and content retrieval.

4. **Configure user settings**: Update RAGapp's user interface to allow users to select their preferred AI provider (either OpenAI or Azure OpenAI) and configure relevant settings accordingly. This might involve adding a new section in the app settings or preferences menu.

5. **Testing and debugging**: Thoroughly test the integration of Azure OpenAI within RAGapp to identify and resolve any potential issues or bugs. This includes testing various scenarios, edge cases, and user interactions to ensure a smooth user experience.

6. **Documentation and user guidance**: Update RAGapp's documentation, tutorials, and user guides to provide instructions on how to use Azure OpenAI as an alternative AI provider. This should include information on configuration, usage, and troubleshooting.

7. **Release and announcement**: Once the integration is complete and thoroughly tested, release the updated version of RAGapp with support for Azure OpenAI. Announce this new feature to users through release notes, blog posts, social media, and other communication channels.

8. **Gather feedback and iterate**: Encourage users to provide feedback on their experience with Azure OpenAI integration. Use this feedback to make further improvements and iterations to enhance the functionality and usability of RAGapp's support for Azure OpenAI.

By following these steps, you can successfully expand RAGapp's AI provider support to include Azure OpenAI, providing users with more choices and enhancing the versatility of the application.

**Comment by marcusschiesser** [comment]
Good news, we just build a test release containing the Azure OpenAI support:

![image](https://github.com/ragapp/ragapp/assets/17126/8e08e55a-8936-48c6-846e-1a8170399c68)

To test it, you'll need to pull from Github's container registry:
```
docker pull ghcr.io/ragapp/ragapp:latest
docker run -p 8000:8000 ghcr.io/ragapp/ragapp:latest
```
see https://github.com/ragapp/ragapp/pkgs/container/ragapp

**Comment by benemanu** [comment]
When using the text-embedding-ada-002 model, I get this error. The qdrant db configures with 768 instead of 1536 dims.

"WARN collection::collection_manager::collection_updater: Update operation declined: Wrong input: Vector dimension error: expected dim: 768, got 1536."

**Comment by marcusschiesser** [comment]
@benemanu you're using the docker compose file? that's not for Azure, it's for Ollama. You can try replacing 768 with 1536 in the docker compose file.

**Comment by marcusschiesser** [comment]
@benemanu just call `docker run -p 8000:8000 ragapp/ragapp:latest`. The latest release has now Azure OpenAI included (that's why I am closing this ticket).
