### ISSUE TITLE
Turn on/off Next questions feature and be able modify to modify its prompt

### ISSUE THREAD

**Issue by Rauljauregi** [ragapp/ragapp#163]
First of all, thank you for the excellent work on RagApp. I'm currently integrating it into my stack, and I've noticed a few areas where I'd like to fine-tune the experience before presenting it to end users. My goal is to make sure the application is as user-friendly as possible so that, if they find it useful, they can start using it regularly.

Areas for Refinement:

PDF Document Management:
When uploading PDF files in the admin panel, I'm unsure of the best practices for formatting these documents to ensure optimal results within RagApp. Could you provide some recommendations or guidelines for this?

Event Display in Chat:
The "Show events" feature in the chat is very insightful, but I believe it might be overwhelming for an end user. I've been manually hiding these events by modifying files and placing them in the 'Patch' folder. It would be helpful to have a more straightforward way to manage this, perhaps with an option to toggle these events on or off.

Node Content Linking:
Currently, the node content links (the numbers pointing to "Node content") direct users to the entire document instead of the specific paragraph. This might be confusing or overwhelming for end users. I believe a more precise linking method would enhance the user experience.

Final Questions Accuracy:
The final questions generated by the LLM are great, but I have some doubts about their accuracy. I would appreciate having the ability to review, modify, or even hide these questions as needed.

Expected Outcome: I am seeking advice on how to best format PDF documents for integration into RagApp and suggestions on how to streamline the user interface to make it more intuitive for end users. Ultimately, I want to ensure that the application is polished and user-friendly before introducing it to clients.

**Comment by marcusschiesser** [comment]
@Rauljauregi, thanks for your suggestions. It's usually best to create one issue per topic. Here are my thoughts:

>PDF Document Management:
You get the best results using LlamaParse

>Event Display in Chat
needs to be restructured as part of adding multi-agents

> Node Content Linking
yes, we'll need that in create-llama first, feel free to open a ticket at github.com/run-llama/create-llama/issues 

>Final Questions Accuracy
Let's work on this in this ticket. It makes sense to turn it on/off in the UI and be able to modify the associated system prompt
