### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by mrt2081** [ragapp/ragapp#164]
When uploading multiple files, the file upload API is called for each file individually, and the data folder is reindexed each time. Consequently, if you upload a large number of files, the data reindexing process occurs repeatedly, which can be inefficient.

**Comment by marcusschiesser** [comment]
@mrt2081 you mentioned you have a PR for this?

**Comment by mrt2081** [comment]
@marcusschiesser Yes, I have fixed that, however, my fork is private and so far, I could not find a solution to open a pr from that to your repo

**Comment by marcusschiesser** [comment]
I see I think you need to rename your private fork and make a new public fork

**Comment by mrt2081** [comment]
@marcusschiesser https://github.com/ragapp/ragapp/pull/196
