### ISSUE TITLE
Knowledge base parsing failed

### ISSUE THREAD

**Issue by Upcreat** [ragapp/ragapp#17]
When deployed using Dcoker, the chat process is normal, but an error occurs during the loading and uploading of the knowledge base. The error is as follows:![1716718316605](https://github.com/ragapp/ragapp/assets/83943594/8f7dfba3-1919-490c-b413-ac6f8ef0677c)

**Comment by marcusschiesser** [comment]
@Upcreat thanks for the bug report. The error comes from Ollama generating the embedding for your text. Maybe our embedding model (`nomic-embed-text`) is not working with Chinese? We're working on making the embedding model configurable

**Comment by Upcreat** [comment]
> @Upcreat thanks for the bug report. The error comes from Ollama generating the embedding for your text. Maybe our embedding model (`nomic-embed-text`) is not working with Chinese? We're working on making the embedding model configurable

thank you for your reply!  It's not a Chinese embedding problem, because I used an English paper for Q&A, and vector embedding is also not possible. The reason is not yet known, but the construction method is:docker run -p 8000:8000 ragapp/ragapp
![image](https://github.com/ragapp/ragapp/assets/83943594/174b9a97-f274-480a-b307-1934c5f7fcd4)

**Comment by leehuwuj** [comment]
Hi @Upcreat , Thanks for the extra info. Seems like it's a bottleneck issue with Ollama, since it could generate embeddings for some pages (2% or 40% in your first image). How did you set up the Ollama server? Did it utilize the GPU resource?

**Comment by leehuwuj** [comment]
@Upcreat Thanks for the information! Not sure this approach can fix your issue with Ollama but you can try reducing the chunk size to fit the model with your resource by setting the `CHUNK_SIZE` environment variable: `docker run -p 8000:8000 -e CHUNK_SIZE=512 ragapp/ragapp` (the default size is 1024). 

Because it's an Ollama issue, I'll close this ticket.

**Comment by kwaljee** [comment]
@Upcreat, try updating nomic-embed text via Ollama models; this seemed to do the trick for me. I just pulled ollama pull nomic-embed-text again and I was able to successfully upsert documents.
