### ISSUE TITLE
Local Customization: Missing Module 'app' During App Creation

### ISSUE THREAD

**Issue by Rauljauregi** [ragapp/ragapp#177]
**Describe the bug**
When attempting to customize the application and create it locally, a `ModuleNotFoundError` occurs indicating that the module 'app' cannot be found (even the file and path is there). This error arises after running the `make dev` command, which prevents the application from running correctly.

**To Reproduce**
1. Clone the project repository and switch to the desired branch.
2. Customize the app by running the `make build-frontends` command to build the frontend.
3. Attempt to start the app locally by running the `make dev` command.
4. The error `ModuleNotFoundError: No module named 'app'` appears, indicating a missing module.

**Expected behavior**
The application should start successfully without any missing module errors after running the `make dev` command, allowing for local development and customization.

**Screenshots**
![issue-customization-ragapp](https://github.com/user-attachments/assets/4c35b39c-37f8-4d25-83b4-8eb0272a4845)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Versión 128.0.6613.120 (Build oficial) (64 bits)
- Version: Python 3.12.6, Poetry 1.8.1

**Additional context**
This issue seems related to the Python path or missing dependencies when customizing and building the application locally. It may involve conflicts or missing configurations in the `pyproject.toml` or `Makefile`. The issue persists even after reinstalling dependencies and ensuring the correct Python environment.

**Comment by leehuwuj** [comment]
I really recommend using Linux, MacOS, or WSL (Windows Subsystem for Linux) for development. 
From your screenshot, it seems like you’ve got the wrong PYTHONPATH set. It should be ./create_llama/backend, but you’re missing the dot symbol `.`. Ideally, this should be in the Makefile, but I think the dot symbol might not work on cmd and powershell.

**Comment by Rauljauregi** [comment]
Thank you for the prompt support. It turns out the issue was on my end. Everything is working perfectly now. I appreciate your help, and I'll go ahead and close the issue. Thanks again!
