### ISSUE TITLE
Is Ollama available?

### ISSUE THREAD

**Issue by felipec23** [ragapp/ragapp#2]
**Describe the bug**
Ollama is not available when selecting the model provider.
(I see one of the last PRs to be about adding Ollama). Is it still not fully ready?

**To Reproduce**
1. Running the docker command and then going to the UI.
2. Running the development installation steps and then going to the UI.

**Expected behavior**
Ollama should appear as a model provider. 

Thanks!

**Comment by marcusschiesser** [comment]
@felipec23 Thanks for the suggestion. It's now in the 0.0.7 release - so don't forget to `docker pull ragapp/ragapp:latest` 😆
