### ISSUE TITLE
Gemini model selection error

### ISSUE THREAD

**Issue by IsaacGreenMachine** [ragapp/ragapp#20]
**Describe the bug**
Error is raised for missing image to `gemini-pro-vision` when `gemini-pro` is selected in admin panel.  

**To Reproduce**
1. launch app with `docker run -p 8000:8000 ragapp/ragapp`
2. open admin admin panel at `http://0.0.0.0:8000/admin/`
3. Follow settings:
   a. Model Provider: `Gemini` 
   b. API key (verified it works with curl request)
   c. model `gemini-pro`
   d. custom prompt (same as default) `You are a helpful assistant who helps users with their questions.`
   e. disable `DuckDuckGo` and `Wikipedia` in Agent Config
   f. upload one PDF to ```Knowledge```
   g. enter question and press `Send Message`
   

**Expected behavior**
response should be generated based on the question. Instead, an error is thrown
`google.api_core.exceptions.InvalidArgument: 400 Add an image to use models/gemini-pro-vision, or switch your model to a text model.`

**Screenshots**

**Desktop**
 - OS: Mac
 - Browser: Firefox
 - Version: 126

**Comment by leehuwuj** [comment]
Hi @IsaacGreenMachine, the issue's been fixed (https://github.com/ragapp/ragapp/pull/12, https://github.com/ragapp/ragapp/issues/11) and will be in the next release. Thanks for the heads up!

**Comment by titouv** [comment]
I had the same issue a few minutes before you closed it and I explored this rabbit hole.

I think the issue comes from the `llama_index` repo with the following issue https://github.com/run-llama/llama_index/issues/13573

There is my [pull request](https://github.com/run-llama/llama_index/pull/13791 ) to try to fix this at the root, though it could be useful to have a temporary fix because this could be considered a breaking change and take some time to be merge

**Comment by IsaacGreenMachine** [comment]
got it. Thanks!

**Comment by marcusschiesser** [comment]
Reopening as not released yet

**Comment by marcusschiesser** [comment]
Good news, we just built a test release fixing the Gemini error.

To test it, you'll need to pull from Github's container registry:
```
docker pull ghcr.io/ragapp/ragapp:latest
docker run -p 8000:8000 ghcr.io/ragapp/ragapp:latest
```
see https://github.com/ragapp/ragapp/pkgs/container/ragapp

**Comment by marcusschiesser** [comment]
Feature is released, closing
