### ISSUE TITLE
Source files not opened

### ISSUE THREAD

**Issue by Rauljauregi** [ragapp/ragapp#223]
Documents returned as sources are not opened on the frontend, At least when deployed on a server.

Even the pdf is not previewed in the side expanding panel. This in multi ragapps deployment in a server

**Comment by Rauljauregi** [comment]
I think it is the configuration of allowed permission and routes. But cannot solve. Do you plan to solve this?

**Comment by marcusschiesser** [comment]
I am not sure I 100% understand the issue. Do you have a step-by-step test case with some screenshots?

**Comment by Rauljauregi** [comment]
I am trying to download the pdf sources upload in the knowledge base in admin panel.

<iframe src="https://scribehow.com/embed/Download_PDF_File_From_Vialabs_Digital_App__4HNW3kKuT9mNt4pjwcLjHA?as=video" width="100%" height="640" allowfullscreen frameborder="0"></iframe>

**Comment by Rauljauregi** [comment]
I am sorry to say that is not working. I have clone the last version, and reviewed everything but cannot see the solution:

# Accessing a PDF File on a Website
####


1\. Navigate to [.../a/test/)


2\. Click here.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-11-04/eeb0682c-64b4-49d5-9308-82fb098f34fe/ascreenshot.jpeg?tl_px=11,379&br_px=870,860&force_format=jpeg&q=100&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


3\. Click here.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-11-04/5643a39a-91b0-4892-952c-f21863b22af3/ascreenshot.jpeg?tl_px=0,110&br_px=859,591&force_format=jpeg&q=100&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=263,212)


4\. Click "/api/files/data/Attention Is All You Need.pdf"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-11-04/c3fb8e60-21bd-4f38-a6c6-2fc8420372a0/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=jpeg&q=100&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=253,119)


5\. Click "404 page not found"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-11-04/5813fb08-faac-4fb7-b980-6164d99b17bf/ascreenshot.jpeg?tl_px=134,0&br_px=993,480&force_format=jpeg&q=100&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,103)

**Comment by marcusschiesser** [comment]
Problem seems to be that the relative URL is missing the prefix from the manager

**Comment by Rauljauregi** [comment]
Anyway when clicking on the link, it does open the browser with the prefix (the domain name + the relative path that is showed in the image) and the result in the browser is a 404.

Tell me if I can help or provide more info. I can share in private the URL to the installation just in case you need to do other testing.

**Comment by Rauljauregi** [comment]
Hi, thank you for this amazing project!  I’m wondering if this is something that might be resolved soon or if it’s expected to take significant effort, would appreciate any updates or insights on this. Thanks again for your great work!

**Comment by Rauljauregi** [comment]
The issue has been resolved. The root cause was corrupted containers and images in the environment. After cleaning up and rebuilding the affected images and containers, everything is working as expected. Thank you for your support!
