### ISSUE TITLE
The chat doesn't answer 

### ISSUE THREAD

**Issue by lilgehan** [ragapp/ragapp#24]
Hello, 
I did all the steps described and arrived to http://[localhost:8000/admin/](http://localhost:8000/admin/), also I chose Gemini and provided a key, but the chat doesn't anser to any question. 

![Capture d'écran 2024-05-29 224246](https://github.com/ragapp/ragapp/assets/171183111/d7dff6c1-e835-4a51-9b80-90df495f433c)

**Comment by marcusschiesser** [comment]
@lilgehan I guess that's related to https://github.com/ragapp/ragapp/issues/20 - if not please reopen
