### ISSUE TITLE
Deploy to hugging face

### ISSUE THREAD

**Issue by khanhthanhdev** [ragapp/ragapp#255]
I have tried to deploy in Render but 512mb ram is not enough
When i deploy to hugging face space, it has some problems
Is there anyone have do that ?

**Comment by leehuwuj** [comment]
Yes, 512mb ram is a bit tough to run. Which deployment kind did you use and what issue did you run into when deploying to HuggingFace? 
You can also use my template: https://huggingface.co/spaces/leehuwuj/ragapp
