### ISSUE TITLE
Local Ollama is too slow - increase time out and make it configurable

### ISSUE THREAD

**Issue by pixelpunch** [ragapp/ragapp#29]
I am on MacOS 12.7.4 (Monterey)
I have Ollama 0.1.39 installed 
I have Docker desktop 26.1.1 with docker console
I have a PDF document uploaded for the AI to read

I am able to get the app loaded on the browser but it doesn’t do anything when I put in the query/message

On http://host.docker.internal:11434 - I get an error - “the site can’t be reached’
On http://localhost:11434/ - I get ‘Ollama is running’

The query/message is 'In which week do we do pages 30 - 40?' which appears in line 2024-05-31 15:36:01

Here is the terminal output attached
[no app response.pdf](https://github.com/user-attachments/files/15514919/no.app.response.pdf)

<img width="2102" alt="Screenshot 2024-05-31 at 15 39 41" src="https://github.com/ragapp/ragapp/assets/7808050/03be334a-6fbe-4ef7-9ef1-bef827cd06c6">

**Comment by marcusschiesser** [comment]
Using http://host.docker.internal:11434 is correct.

The log shows that you're getting a "httpx.ReadTimeout: timed out" error so your Ollama is too slow generating the tokens.

I have a M2 with 24GB,  llama3 works ok there, but generally the more GPU compute and RAM the better.

**Comment by pixelpunch** [comment]
Thanks. I will try on a M2 16GB and see if it works.

**Comment by DanFitzgibbon** [comment]
I'm not sure if this is related to OP or whether it's actually useful but on Ubuntu, I had to add a different argument to connect to host:
`docker run --network host ragapp/ragapp`
With this, I was able to use `http://localhost:11434` as the Base URL to get it to work.

**Comment by yodamad** [comment]
> The log shows that you're getting a "httpx.ReadTimeout: timed out" error so your Ollama is too slow generating the tokens.

Is it possible to extend timeout ?

**Comment by marcusschiesser** [comment]
@yodamad makes sense - I changed the ticket title

**Comment by yodamad** [comment]
@marcusschiesser great, thank you

**Comment by pixelpunch** [comment]
@marcusschiesser just wanted to report back that local llama runs on a Mac M2/16GB RAM but not on an older/slower machine

**Comment by marcusschiesser** [comment]
@pixelpunch thanks, but we still should make the timeout configurable so I am reopening

**Comment by marcusschiesser** [comment]
<img width="755" alt="image" src="https://github.com/ragapp/ragapp/assets/17126/4a8e04ef-2a15-4283-9397-9cc8e52c571e">
Now you can configure the timeout in v0.0.9

**Comment by yodamad** [comment]
Great, I'll try it soon
