### ISSUE TITLE
Troubleshooting setup-1 container errors on Windows 11 with Nvidia GPU and 16GB RAM

### ISSUE THREAD

**Issue by Rauljauregi** [ragapp/ragapp#35]
Describe the bug
The setup-1 container is failing to run on a Windows 11 system with an Nvidia GPU and 16GB of RAM due to permission errors when trying to execute the create_qdrant_collection.sh and setup_ollama.sh scripts.

To Reproduce

1. > Clone the project repository to a local directory.
2. > Navigate to the project directory in a terminal. And create de Docker image
3. > Run the command docker-compose up to start the containers.
4. > Observe the error messages in the logs for the setup-1 container.

Expected behavior
The setup-1 container should start successfully and execute the create_qdrant_collection.sh and setup_ollama.sh scripts without any permission errors.

Screenshots
![Captura de pantalla 2024-06-04 192946](https://github.com/ragapp/ragapp/assets/53576209/3cdbd5f2-3313-4470-af6a-fe154d5d7fb8)

Desktop:
OS: Windows 11

Additional context
I have tried running the container with the --user flag, the --privileged flag, and mounting the local directory containing the scripts to a different directory inside the container, but none of these solutions have worked. I have also checked the permissions of the scripts on my local system and they seem to be correct. I am using an Nvidia GPU and have 16GB of RAM on my system.

**Comment by Rauljauregi** [comment]
Any update on this? I cannot test last versions. Or is just my or my computer problem?

Thank you

**Comment by marcusschiesser** [comment]
@Rauljauregi we only have Windows 10 (no Nvidia GPU) and it worked. Someone else who can reproduce the issue? 
Also might be helpful to know what docker version are you running?

You might want to try to comment out the `chmod` line in the `docker-compose.yml` file:
```yaml
    command: >
      /bin/sh -c 
      "/ragapp/create_qdrant_collection.sh &&
      /ragapp/setup_ollama.sh"
```

**Comment by Rauljauregi** [comment]
The problem is that as qdrant colletion is not created I have to do it manually. Which is ok if I use for myself, but yet cannot do what i would like to do, and the super-project RagAPP allows

**Comment by Rauljauregi** [comment]
To be more specific, Docker image works perfectly, congrats. But I try to do some customizations, and later create a new image . But when creating the container fron that new image is when i got the error on the image. 

I thought the customizations (some UI changes) are allowed, isn´t it? thank you again

**Comment by Rauljauregi** [comment]
Maybe issue will be solved if UI customizations can be done by OpenAPI feature.

**Comment by Rauljauregi** [comment]
I am going to close this issue as solved. This was my bad. The real issue is related to running Ollama inside the container. and I see other people telling similar things I will double check this on my side before reporting my troibles. thank you
