### ISSUE TITLE
Add Authentication Scheme to Admin Side

### ISSUE THREAD

**Issue by byamasu-patrick** [ragapp/ragapp#36]
### Description
I would like to propose the addition of an authentication scheme to the admin side of the Ragapp system. This feature is essential to ensure that only authorized personnel can access and manage the administrative functionalities of the system.

### Objectives
- Implement an authentication mechanism for the admin interface.
- Ensure that the authentication process is secure and user-friendly.
- Provide options for different authentication methods (e.g., username/password, OAuth, multi-factor authentication).

### Benefits
- Enhanced security for the admin functionalities.
- Prevention of unauthorized access to sensitive administrative tasks.
- Improved user management and accountability.

### Suggested Implementation Steps
1. Research and select an appropriate authentication method (or methods) for the admin side.
2. Integrate the chosen authentication method into the admin interface.
3. Ensure proper handling of authentication sessions and timeouts.
4. Implement user management features, such as password reset and account recovery.
5. Test the authentication scheme thoroughly to ensure reliability and security.

### Additional Notes
- Consider using existing authentication libraries or frameworks to streamline development.
- Ensure that the user interface for the authentication process is intuitive and accessible.

### References
- [OAuth Documentation](https://oauth.net/documentation/)
- [OWASP Authentication Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html)

**Comment by byamasu-patrick** [comment]
I want to add this, since most of enterprise will choose to have only selected people can have the ability to add or remove contents files that either their employees will have to chat with or normal users. If possible @marcusschiesser can you give a simple guidance on how this can be done on the development environment?

**Comment by Rauljauregi** [comment]
I would want the authentication feature be also added to chat page. This is very useful to make access to knoledge base documentation more private.

Thank you and great job!

**Comment by marcusschiesser** [comment]
I clarified this a bit in https://github.com/ragapp/ragapp?tab=readme-ov-file#authentication - please have a look. What cloud environments are you using?

**Comment by marcusschiesser** [comment]
Please have a look at https://github.com/ragapp/ragapp/tree/main/deployments/multiple-ragapps - it's a deployment that is supporting authentication
