### ISSUE TITLE
ragapp does not recognize the files uploaded

### ISSUE THREAD

**Issue by arvindkc** [ragapp/ragapp#37]
**Describe the bug**

1. I uploaded files via the "knowledge panel" and when I try to query it, the app does not read it. 
2. I also get the upload file modal when I click the attach icon but it does not actually upload the tile. 

**To Reproduce**
1. Upload a file in the knowledge panel and try to query it. That would fail
2. Try uploading a file by clicking the attachment option in chat in the admin window
3. 
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Arc

**Comment by leehuwuj** [comment]
@arvindkc 
About 1. Which model provider are you using, and do you have any error logs in the console?
for 2. , The attachment icon in the chat UI does not work the same as the knowledge upload in Admin UI. It's only able to upload an image and chat with the image.

**Comment by marcusschiesser** [comment]
@arvindkc in v0.0.9 there should be now an error for unsupported file types (only .csv is allowed at the moment)

**Comment by ns-ffx** [comment]
@marcusschiesser is there a documentation about how the knowledge needs to be organised for ragapp? we used for now normal txt files and pdfs. But since i read your comment here, is it better or only allowed to use csv? Does every fact need to be a own comma seperated value? Thank you in advance!

**Comment by marcusschiesser** [comment]
@ns-ffx sorry, my comment is about the user upload - that one only supports .csv files at the moment

**Comment by marcusschiesser** [comment]
@arvindkc with which file types do you have issues with uploading to the knowledge base?

**Comment by marcusschiesser** [comment]
closing as test case missing
