### ISSUE TITLE
Add Llama_parse in admin

### ISSUE THREAD

**Issue by Rauljauregi** [ragapp/ragapp#38]
**Is your feature request related to a problem? Please describe.**
I would like to have the posibility to set of Llama Parse to improve indexing

**Describe the solution you'd like**
I would like to suggest the addition the feature that allows select llamaparse

**Describe alternatives you've considered**
I was not able to make it work, maybe i made something wrong

**Additional context**
I tried setting llama_parse: true on loader.yaml and in the .env file the api key, but didn´t work

**Comment by gillesdeperetti** [comment]
Hello @Rauljauregi 

Do we have the same issue ? : #39

**Comment by Rauljauregi** [comment]
Hello @gillesdeperetti it is quite similar. But in my case it is not working at all even if i desindex files. In my case i configures Llama_parse setting in .env file inside config and loader.py to 'true'. Hope it is solve for both.

thnk you for sharing
