### ISSUE TITLE
Option to have custom OpenAI endpoint to support OpenAI Instance behind a LB/Proxy 

### ISSUE THREAD

**Issue by ChennaiTechie** [ragapp/ragapp#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Option to configure a specific endpoint that is behind a LB/Proxy

**Comment by marcusschiesser** [comment]
@ChennaiTechie which proxy are you using? Do you have some sample code to use the proxy?

**Comment by ChennaiTechie** [comment]
import openai
openai.api_type = "azure"
openai.api_key = "..."
openai.api_base = "https://example-endpoint.openai.azure.com"
openai.api_version = "2022-12-01"

openai.api.base we have proxy endpoint 
https://github.com/uezo/aiproxy similar to this approach

**Comment by marcusschiesser** [comment]
implemented in v0.0.12
