### ISSUE TITLE
Option to upload multiple files for RAG 

### ISSUE THREAD

**Issue by ChennaiTechie** [ragapp/ragapp#58]
**Is your feature request related to a problem? Please describe.**
Uploading multiple sets of files is not currently possible it removes the previously uploaded file

**Comment by leehuwuj** [comment]
Hi @ChennaiTechie, can you share more details about your issue? I tried with the latest version and couldn't reproduce it. By the way, we use the file name as an ID, so you can't upload the same file twice. 
A good news is we're improving the file uploader, so we'd love to hear your feedback!

**Comment by leehuwuj** [comment]
Looks like the new version has fixed your issue! Let give it a try https://github.com/ragapp/ragapp/releases/tag/v0.0.11. Thanks!
