### ISSUE TITLE
Suggest adding the api host parameter to facilitate requesting API interfaces of different large models using proxy addresses

### ISSUE THREAD

**Issue by soluckysummer** [ragapp/ragapp#69]
Suggest adding the api host parameter to facilitate requesting API interfaces of different large models using proxy addresses
![image](https://github.com/ragapp/ragapp/assets/120010264/94e929c8-309d-4707-b5a7-aad84b2c2793)

**Comment by marcusschiesser** [comment]
implemented in v0.0.12
