### ISSUE TITLE
Implement GROQ API

### ISSUE THREAD

**Issue by coderjunc** [ragapp/ragapp#79]
As you may know, OpenAI's models are renowned for their robustness and accuracy in natural language processing tasks. However, one of the challenges faced is the inference speed required to deliver real-time or near real-time responses in applications like RAG. GroqAI's architecture offers a notable advantage in this regard, with its specialized hardware designed to accelerate inference tasks.

By incorporating GroqAI alongside OpenAI, the RAG app could achieve faster response times without compromising on the quality of generated outputs. This enhancement not only enhances user experience by reducing latency but also expands the applicability of RAG in high-demand scenarios such as interactive customer support, real-time content generation, and more.

So, I would request you to implement it asap!

Thanks.

**Comment by leehuwuj** [comment]
We've been working on this, but it's not ready to merge yet. You can track it here: https://github.com/ragapp/ragapp/pull/54

**Comment by coderjunc** [comment]
I would like to use a GROQ for generation. For embedding, I would prefer either OpenAI or ideally **Cohere Embed**. Do you have plans to implement a **Reranker**? The semantic search is not very accurate. Also, it would be helpful if you could publish RAGAPP's architecture diagram so that it would be easier to understand the flow.

**Comment by marcusschiesser** [comment]
@coderjunc Adding a reranker is a good idea, can you open another ticket for this? 

About GROQ: The problem is that it doesn't support an embedding yet. We'll add it as soon as it does.
An alternative would be to configure the embedding and the LLM separately. But that would complicate the setup of RAGapp and the main idea of RAGapp is to keep it as simple as possible

**Comment by marcusschiesser** [comment]
I think as GROQ doesn't have an embedding model, we could try https://github.com/qdrant/fastembed - seems to use less resources than HF

**Comment by pixelpunch** [comment]
@marcusschiesser - a query related to qdrant - any specific reason why qdrant is being used as a vector search database? If I deploy the app to AWS, then I would prefer to keep everything in one place and use Amazon OpenSearch Serverless instead. Any downside to that?
