### ISSUE TITLE
Problem on Coolify

### ISSUE THREAD

**Issue by DannyBoy5240** [ragapp/ragapp#83]
I'm trying to deploy Ragapp on Coolify. 
But it doesn't work well, it displays error message whatever I do.
I think it can't communicate each other.
I want to know how to set docker compose file for this.

I set the last domain for ragapp.
Do I have to set each domain?

![image](https://github.com/ragapp/ragapp/assets/114929153/c62c6aef-cd19-4f7c-99dd-9f0632634630)

This is the error.
![image](https://github.com/ragapp/ragapp/assets/114929153/745b2382-8d27-43e3-8503-f2bed1bb9c2f)

**Comment by DannyBoy5240** [comment]
This is the error.
![image](https://github.com/ragapp/ragapp/assets/114929153/d865a228-a3bf-415d-9f9c-ab64af896356)

**Comment by marcusschiesser** [comment]
closing (sorry, don't know coolify)
