### ISSUE TITLE
Is there any way to use the OpenAI embedding model?

### ISSUE THREAD

**Issue by Hangsiin** [ragapp/ragapp#86]
When uploading a knowledge base, the upload of a .docx file fails.
Maybe it's because the filename and file contents are in Korean.
It would be nice to be able to build a vector database using OpenAI's embedding model, for example "text-embedding-3-small", is this possible?

**Comment by leehuwuj** [comment]
Hi @Hangsiin, We're already using the `text-embedding-3-small` as the default embedding model for the OpenAI provider.
About your issue, what's the error you're getting with the .docx file? Can you share the error log in the console?

**Comment by marcusschiesser** [comment]
@Hangsiin you can select the model used in the new release
