### ISSUE TITLE
Release 0.0.14 broke the LlamaParse functionality

### ISSUE THREAD

**Issue by tvlc** [ragapp/ragapp#97]
**Describe the bug**
Release 0.0.14 - support for LlamaCloud hosting - broke the functionality of using llama_parse

**To Reproduce**
1. Go to admin panel
2. Leave Use LlamaCloud OFF
3. Set Use LlamaParse ON
4. Enter LlamaCloud API Key
5. Click on Upload File and select local pdf for upload
6. Upload fails with error

**Expected behavior**
File gets uploaded and parsed

**Additional context**
See logged errors:

ragapp-1  | INFO:     192.168.65.1:40476 - "POST /api/management/loader HTTP/1.1" 200 OK
ragapp-1  | INFO:     192.168.65.1:40476 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
ragapp-1  | INFO:     192.168.65.1:32161 - "POST /api/management/loader HTTP/1.1" 200 OK
ragapp-1  | INFO:     192.168.65.1:32161 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
ragapp-1  | INFO:root:Generate index for the provided data
ragapp-1  | INFO:app.engine.loaders:Loading documents from loader: file, config: {'use_llama_parse': True}
ragapp-1  | Error while parsing the file '<bytes/buffer>': file_input must be either a file path string, file bytes, or buffer object
ragapp-1  | INFO:     192.168.65.1:60074 - "POST /api/management/files HTTP/1.1" 500 Internal Server Error
ragapp-1  | ERROR:    Exception in ASGI application
ragapp-1  | Traceback (most recent call last):
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 538, in load_file
ragapp-1  |     docs = reader.load_data(input_file, **kwargs)
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_parse/base.py", line 340, in load_data
ragapp-1  |     return asyncio.run(self.aload_data(file_path, extra_info))
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
ragapp-1  |     return loop.run_until_complete(task)
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
ragapp-1  |     return f.result()
ragapp-1  |            ^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/asyncio/futures.py", line 203, in result
ragapp-1  |     raise self._exception.with_traceback(self._exception_tb)
ragapp-1  |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 277, in __step
ragapp-1  |     result = coro.send(None)
ragapp-1  |              ^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_parse/base.py", line 301, in aload_data
ragapp-1  |     return await self._aload_data(
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_parse/base.py", line 292, in _aload_data
ragapp-1  |     raise e
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_parse/base.py", line 267, in _aload_data
ragapp-1  |     job_id = await self._create_job(file_path, extra_info=extra_info)
ragapp-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_parse/base.py", line 179, in _create_job
ragapp-1  |     raise ValueError(
ragapp-1  | ValueError: file_input must be either a file path string, file bytes, or buffer object
ragapp-1  |
ragapp-1  | The above exception was the direct cause of the following exception:
ragapp-1  |
ragapp-1  | Traceback (most recent call last):
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
ragapp-1  |     result = await app(  # type: ignore[func-returns-value]
ragapp-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
ragapp-1  |     return await self.app(scope, receive, send)
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
ragapp-1  |     await super().__call__(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
ragapp-1  |     await self.middleware_stack(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
ragapp-1  |     raise exc
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
ragapp-1  |     await self.app(scope, receive, _send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
ragapp-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
ragapp-1  |     raise exc
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
ragapp-1  |     await app(scope, receive, sender)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
ragapp-1  |     await self.middleware_stack(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
ragapp-1  |     await route.handle(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
ragapp-1  |     await self.app(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
ragapp-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
ragapp-1  |     raise exc
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
ragapp-1  |     await app(scope, receive, sender)
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
ragapp-1  |     response = await func(request)
ragapp-1  |                ^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
ragapp-1  |     raw_response = await run_endpoint_function(
ragapp-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
ragapp-1  |     return await dependant.call(**values)
ragapp-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/app/src/routers/management/files.py", line 22, in add_file
ragapp-1  |     res = await FileHandler.upload_file(file, str(file.filename))
ragapp-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/app/src/controllers/files.py", line 49, in upload_file
ragapp-1  |     index_all()
ragapp-1  |   File "/app/src/tasks/indexing.py", line 12, in index_all
ragapp-1  |     generate_datasource()
ragapp-1  |   File "/app/create_llama/backend/app/engine/generate.py", line 66, in generate_datasource
ragapp-1  |     documents = get_documents()
ragapp-1  |                 ^^^^^^^^^^^^^^^
ragapp-1  |   File "/app/create_llama/backend/app/engine/loaders/__init__.py", line 28, in get_documents
ragapp-1  |     document = get_file_documents(FileLoaderConfig(**loader_config))
ragapp-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/app/create_llama/backend/app/engine/loaders/file.py", line 66, in get_file_documents
ragapp-1  |     raise e
ragapp-1  |   File "/app/create_llama/backend/app/engine/loaders/file.py", line 51, in get_file_documents
ragapp-1  |     return reader.load_data()
ragapp-1  |            ^^^^^^^^^^^^^^^^^^
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 688, in load_data
ragapp-1  |     SimpleDirectoryReader.load_file(
ragapp-1  |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 545, in load_file
ragapp-1  |     raise Exception("Error loading file") from e
ragapp-1  | Exception: Error loading file
ragapp-1  | INFO:root:Generate index for the provided data
ragapp-1  | INFO:app.engine.loaders:Loading documents from loader: file, config: {'use_llama_parse': True}
ragapp-1  | WARNING:app.engine.loaders.file:Failed to load file documents, error message: No files found in data. . Return as empty document list.
ragapp-1  | INFO:app.engine.vectordb:Using vector provider: qdrant
qdrant-1  | 2024-07-05T17:42:56.810086Z  INFO actix_web::middleware::logger: 172.19.0.5 "GET /collections/default/exists HTTP/1.1" 200 82 "-" "python-httpx/0.27.0" 0.000596
ragapp-1  | INFO:httpx:HTTP Request: GET http://qdrant:6333/collections/default/exists "HTTP/1.1 200 OK"
Parsing nodes: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
qdrant-1  | 2024-07-05T17:42:56.813124Z  INFO actix_web::middleware::logger: 172.19.0.5 "GET /collections/default/exists HTTP/1.1" 200 79 "-" "python-httpx/0.27.0" 0.000089
ragapp-1  | INFO:httpx:HTTP Request: GET http://qdrant:6333/collections/default/exists "HTTP/1.1 200 OK"
qdrant-1  | 2024-07-05T17:42:56.814210Z  INFO actix_web::middleware::logger: 172.19.0.5 "GET /collections/default HTTP/1.1" 200 420 "-" "python-httpx/0.27.0" 0.000315
ragapp-1  | INFO:httpx:HTTP Request: GET http://qdrant:6333/collections/default "HTTP/1.1 200 OK"
ragapp-1  | INFO:root:Finished generating the index
ragapp-1  | INFO:     192.168.65.1:57919 - "DELETE /api/management/files/4783_pGDx_Touch_End_User_Manual_rev008_20240326_RAG.pdf HTTP/1.1" 200 OK

**Comment by tvlc** [comment]
The exception is raised by **create_llama, file templates/components/loaders/python/file.py**. Call to **get_file_documents(config: FileLoaderConfig)** fails with exception _Error while parsing the file '<bytes/buffer>': file_input must be either a file path string, file bytes, or buffer object_

**Comment by tvlc** [comment]
The root cause is in llama_parse, see https://github.com/run-llama/llama_parse/issues/268 and related pull request.

**Comment by leehuwuj** [comment]
@tvlc Sorry for the issue. I created a PR to llama_parse to fix that, we will upgrade llama_parse once the new version is released

**Comment by mingjun1120** [comment]
@tvlc, I am also facing the same issue as you now.

**Comment by marcusschiesser** [comment]
fixed in v0.0.15 - please try again
